### ISSUE TITLE
"Unsupported macOS Version"

### ISSUE THREAD

**Issue by billiegoose** [fuse-friends/fuse-native#2]
Am I doing something obviously wrong?

```
> node index.js
{ Error [fuse failed]: fuse failed
    at fs.stat (/Users/wmhilton/code/wmhilton/foofs/node_modules/fuse-native/index.js:241:19)
    at FSReqWrap.oncomplete (fs.js:154:5) code: 'fuse failed', name: 'Error [fuse failed]' }
```

![image](https://user-images.githubusercontent.com/587740/71223419-f2fd7f80-22a1-11ea-85b2-28d1b510d965.png)

```
> node -v
v10.15.3
> npm ls
foofs@0.0.0 /Users/wmhilton/code/wmhilton/foofs
└─┬ fuse-native@2.0.2
  ├─┬ fuse-shared-library@1.0.2
  │ ├── fuse-shared-library-darwin@1.0.3
  │ └── fuse-shared-library-linux@1.0.1
  ├─┬ nanoresource@1.3.0
  │ └── inherits@2.0.4
  ├── napi-macros@2.0.0
  └── node-gyp-build@4.2.0
```

macOS Catalina, Version 10.15.2 (19C57)

**Comment by mafintosh** [comment]
Let's see if we can get to the bottom of that. It should work on Catalina. Did you have FUSE installed previously?

**Comment by billiegoose** [comment]
Maybe? I'll look, maybe I installed it with Homebrew a while back or something.
